name: CI Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - "dev"
      - "main"
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (Gradle needs Java to build)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # Install Gradle
      - name: Install Gradle
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.5.1  # Adjust the version based on your project needs

      # Set up environment variables for signing and Maven credentials
      - name: Set up signing and Maven credentials
        run: |
          echo "$SIGNING_KEY" | base64 -d > secret.gpg
          echo "$SIGNING_KEYID" > signing.keyId
          echo "$SIGNING_PASSWORD" | base64 -d > signing.password
          echo "$MAVEN_USERNAME" > maven.username
          echo "$MAVEN_PASSWORD" | base64 -d > maven.password
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      # Set up Gradle properties for signing and Maven credentials
      - name: Set up Gradle local.properties
        run: |
          echo "signing.keyId=$(cat signing.keyId)" > local.properties
          echo "signing.password=$(cat signing.password)" >> local.properties
          echo "signing.secretKeyRingFile=secret.gpg" >> local.properties
          echo "maven_username=$(cat maven.username)" >> local.properties
          echo "maven_password=$(cat maven.password)" >> local.properties

      # Run Gradle build (clean, build, and publish)
      - name: Run Gradle build and publish
        run: |
          ./gradlew clean build publish

      # Clean up sensitive files
      - name: Clean up
        run: |
          rm -f secret.gpg signing.keyId signing.password maven.username maven.password

    
